### ISSUE TITLE
Day 3, step 6, letsencrypt-staging, 

### ISSUE THREAD

**Issue by patrekurs19** [hgop/syllabus-2022#17]
# Expected Behaviour
I am running kubectl apply -f letsencrypt-staging.yaml from step 6 day 3 and i want the following message:
Message: The ACME account was registered with the ACME server

# Current Behaviour
When I do kubectl describe clusterissuer letsencrypt-staging  the message is:
Failed to register ACME account: Get "https://acme-staging-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-staging-v02.api.letsencrypt.org on 127.0.0.53:53: read udp 127.0.0.1:60042->127.0.0.53:53: read: connection refused

## Context

* Operating System: Ubuntu

# Failure Information (for bugs)

## Failure Logs

Please include any relevant log snippets, screen shots or files here.
![Screenshot from 2022-11-24 10-25-53](https://user-images.githubusercontent.com/58478764/203760806-084d5d8a-7a5a-4346-bcb4-e3a988d6f54a.png)
![Screenshot from 2022-11-24 10-26-30](https://user-images.githubusercontent.com/58478764/203760838-9e6800b9-b933-4a4d-a4e6-9a71943f025e.png)

**Comment by Fanneyyy** [comment]
We're not sure what the issue was, but was solved by deleting the cert manager and setting it up again, i.e.
`kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml`
`kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml`
then onwards to, and so on according to the assignment:
`kubectl apply -f letsencrypt-staging.yaml`
